### ISSUE TITLE
Current build need to have local install go instance

### ISSUE THREAD

**Issue by tjyang** [mtojek/greenwall#1]
Hi

Following is error on CentOS 7.3 with default system golang 1.6.3 rpm instance. 
I installed the golang tarball into my $HOME/go to get the build successfully.
Adding this note in readme.md to alert user(beginner like me;) might be helpful.

```
--- PASS: TestLint (8.93s)
PASS
ok      github.com/greenwall    8.932s
?       github.com/greenwall/middleware/application     [no test files]
?       github.com/greenwall/middleware/healthcheck     [no test files]
?       github.com/greenwall/middleware/httpserver      [no test files]
?       github.com/greenwall/middleware/monitoring      [no test files]
go test -race  -i ./...
go install runtime/internal/sys: open /usr/lib/golang/pkg/linux_amd64_race/runtime/internal/sys.a: permission denied
make: *** [test] Error 1
[me@centos7t01 greenwall]$

```

**Comment by mtojek** [comment]
Thank you @tjyang for posting this issue. I've added a side note clarifying this problem.

**Comment by tjyang** [comment]
>As @jtyang spotted - building process may require higher user permission:
it should be @tjyang, not @jtyang. 
No need to bring out my name, please remove the reference to @tjyang ;)

**Comment by mtojek** [comment]
Ok, as you wish @tjyang , but still - thank you for reporting this issue :)

**Comment by tjyang** [comment]
Thanks for your great work. Hopefully I can learn from you to port my health check command line script(in python) to Go.
