### ISSUE TITLE
How to add more health checks beside http/https ?

### ISSUE THREAD

**Issue by tjyang** [mtojek/greenwall#2]
Examples of other health checks like followings:

```
ping
REST query
SOAP query
DNS lookup
```

**Comment by mtojek** [comment]
Hi @tjyang,

thank you for posting this proposal. Actually, this is a great idea, which will extend GreenWall features. I'll add a label to this issue and wait for other proposals to prepare a roadmap.

Thanks

**Comment by kron4eg** [comment]
@mtojek also check for [soon to be] expired SSL certificates would be very nice

**Comment by mtojek** [comment]
@kron4eg Thank you for the proposal - that's a fair point!

**Comment by sajal** [comment]
+1 for DNS/TCP/TLS support. I am in process of moving our infrastructure into Kubernetes and planing to build a similar dashboard for health monitoring.

This project looks like a good fit for monitoring internal endpoints. 

Can the config be updated at runtime?

@mtojek : If you add an example of any other test type, we might be able to contribute code for other tests.

**Comment by mtojek** [comment]
@sajal thank you for this suggestion. It's really worth considering, I'll include this in a feature list.

**Comment by mtojek** [comment]
The implementation has been adjusted to let developers easily create new health check plugins. I'll close this issue as other one has been created for particular plugins. Thanks!
